"""club statistics

Revision ID: 2e8e4d425578
Revises: 
Create Date: 2024-01-24 12:11:54.383332

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2e8e4d425578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    This function upgrades a database table called "club" by adding a new column
    named "bg_statistics" of type JSON with a NULL value.

    """
    op.add_column('club', sa.Column('bg_statistics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    The function `downgrade()` drops a column named "bg_statistics" from a table
    named "club".

    """
    op.drop_column('club', 'bg_statistics')
    # ### end Alembic commands ###
