"""additional league dates

Revision ID: dddf53ed264e
Revises: 2e8e4d425578
Create Date: 2024-01-26 00:09:38.706921

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'dddf53ed264e'
down_revision = '2e8e4d425578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('launch_date', sa.DateTime(), nullable=True))
    op.add_column('league', sa.Column('signup_deadline', sa.DateTime(), nullable=True))
    op.add_column('league', sa.Column('availability_deadline', sa.DateTime(), nullable=True))
    op.add_column('league', sa.Column('schedule_release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'schedule_release_date')
    op.drop_column('league', 'availability_deadline')
    op.drop_column('league', 'signup_deadline')
    op.drop_column('league', 'launch_date')
    # ### end Alembic commands ###
